name: minum
description: A smart water reminder app to keep you hydrated.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2815.1
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  # HTTP Requests
  dio: ^5.4.3+1

  # Local Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3

  # Date & Time
  intl: ^0.20.2

  # Google Sign In
  google_sign_in: ^7.2.0

  # Responsive UI
  flutter_screenutil: ^5.9.0

  # Notifications
  awesome_notifications: ^0.10.1

  # Charts/Graphs
  fl_chart: 1.0.0

  # Package Info
  package_info_plus: ^9.0.0

  # Device Info
  device_info_plus: ^12.1.0

  # Permissions
  permission_handler: ^12.0.0+1

  # Logging
  logger: ^2.2.0

  # Equatable
  equatable: ^2.0.5

  # Connectivity
  connectivity_plus: ^7.0.0


  path: any
  health: ^13.2.1
  flex_color_picker: ^3.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
